// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.3
// source: internals/proto/delete.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table  string     `protobuf:"bytes,1,opt,name=Table,proto3" json:"Table,omitempty"`
	Values []*DValues `protobuf:"bytes,3,rep,name=Values,proto3" json:"Values,omitempty"`
}

func (x *DeleteValues) Reset() {
	*x = DeleteValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internals_proto_delete_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteValues) ProtoMessage() {}

func (x *DeleteValues) ProtoReflect() protoreflect.Message {
	mi := &file_internals_proto_delete_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteValues.ProtoReflect.Descriptor instead.
func (*DeleteValues) Descriptor() ([]byte, []int) {
	return file_internals_proto_delete_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteValues) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *DeleteValues) GetValues() []*DValues {
	if x != nil {
		return x.Values
	}
	return nil
}

type DValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row      string `protobuf:"bytes,1,opt,name=Row,proto3" json:"Row,omitempty"`
	Operator string `protobuf:"bytes,2,opt,name=Operator,proto3" json:"Operator,omitempty"`
	Value    string `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *DValues) Reset() {
	*x = DValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internals_proto_delete_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DValues) ProtoMessage() {}

func (x *DValues) ProtoReflect() protoreflect.Message {
	mi := &file_internals_proto_delete_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DValues.ProtoReflect.Descriptor instead.
func (*DValues) Descriptor() ([]byte, []int) {
	return file_internals_proto_delete_proto_rawDescGZIP(), []int{1}
}

func (x *DValues) GetRow() string {
	if x != nil {
		return x.Row
	}
	return ""
}

func (x *DValues) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *DValues) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool  `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	Amount int32 `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internals_proto_delete_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internals_proto_delete_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_internals_proto_delete_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *DeleteResponse) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_internals_proto_delete_proto protoreflect.FileDescriptor

var file_internals_proto_delete_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46,
	0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x44, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x06,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x4d, 0x0a, 0x07, 0x44, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x52, 0x6f, 0x77, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x40, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x39, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x0d, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a,
	0x0f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x79, 0x61, 0x64, 0x69, 0x69, 0x69, 0x67, 0x2e, 0x64, 0x65,
	0x76, 0x2f, 0x79, 0x64, 0x62, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x73, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internals_proto_delete_proto_rawDescOnce sync.Once
	file_internals_proto_delete_proto_rawDescData = file_internals_proto_delete_proto_rawDesc
)

func file_internals_proto_delete_proto_rawDescGZIP() []byte {
	file_internals_proto_delete_proto_rawDescOnce.Do(func() {
		file_internals_proto_delete_proto_rawDescData = protoimpl.X.CompressGZIP(file_internals_proto_delete_proto_rawDescData)
	})
	return file_internals_proto_delete_proto_rawDescData
}

var file_internals_proto_delete_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internals_proto_delete_proto_goTypes = []interface{}{
	(*DeleteValues)(nil),   // 0: DeleteValues
	(*DValues)(nil),        // 1: DValues
	(*DeleteResponse)(nil), // 2: DeleteResponse
}
var file_internals_proto_delete_proto_depIdxs = []int32{
	1, // 0: DeleteValues.Values:type_name -> DValues
	0, // 1: Delete.DeleteQuery:input_type -> DeleteValues
	2, // 2: Delete.DeleteQuery:output_type -> DeleteResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internals_proto_delete_proto_init() }
func file_internals_proto_delete_proto_init() {
	if File_internals_proto_delete_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internals_proto_delete_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internals_proto_delete_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internals_proto_delete_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internals_proto_delete_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internals_proto_delete_proto_goTypes,
		DependencyIndexes: file_internals_proto_delete_proto_depIdxs,
		MessageInfos:      file_internals_proto_delete_proto_msgTypes,
	}.Build()
	File_internals_proto_delete_proto = out.File
	file_internals_proto_delete_proto_rawDesc = nil
	file_internals_proto_delete_proto_goTypes = nil
	file_internals_proto_delete_proto_depIdxs = nil
}
