// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.3
// source: internals/proto/update.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table    string         `protobuf:"bytes,1,opt,name=Table,proto3" json:"Table,omitempty"`
	Matchers []*MatchValues `protobuf:"bytes,2,rep,name=Matchers,proto3" json:"Matchers,omitempty"`
	Values   []*UValues     `protobuf:"bytes,3,rep,name=Values,proto3" json:"Values,omitempty"`
}

func (x *UpdateValues) Reset() {
	*x = UpdateValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internals_proto_update_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateValues) ProtoMessage() {}

func (x *UpdateValues) ProtoReflect() protoreflect.Message {
	mi := &file_internals_proto_update_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateValues.ProtoReflect.Descriptor instead.
func (*UpdateValues) Descriptor() ([]byte, []int) {
	return file_internals_proto_update_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateValues) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *UpdateValues) GetMatchers() []*MatchValues {
	if x != nil {
		return x.Matchers
	}
	return nil
}

func (x *UpdateValues) GetValues() []*UValues {
	if x != nil {
		return x.Values
	}
	return nil
}

type MatchValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row      string `protobuf:"bytes,1,opt,name=Row,proto3" json:"Row,omitempty"`
	Operator string `protobuf:"bytes,2,opt,name=Operator,proto3" json:"Operator,omitempty"`
	Value    string `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MatchValues) Reset() {
	*x = MatchValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internals_proto_update_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchValues) ProtoMessage() {}

func (x *MatchValues) ProtoReflect() protoreflect.Message {
	mi := &file_internals_proto_update_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchValues.ProtoReflect.Descriptor instead.
func (*MatchValues) Descriptor() ([]byte, []int) {
	return file_internals_proto_update_proto_rawDescGZIP(), []int{1}
}

func (x *MatchValues) GetRow() string {
	if x != nil {
		return x.Row
	}
	return ""
}

func (x *MatchValues) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *MatchValues) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row   string `protobuf:"bytes,1,opt,name=Row,proto3" json:"Row,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *UValues) Reset() {
	*x = UValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internals_proto_update_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UValues) ProtoMessage() {}

func (x *UValues) ProtoReflect() protoreflect.Message {
	mi := &file_internals_proto_update_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UValues.ProtoReflect.Descriptor instead.
func (*UValues) Descriptor() ([]byte, []int) {
	return file_internals_proto_update_proto_rawDescGZIP(), []int{2}
}

func (x *UValues) GetRow() string {
	if x != nil {
		return x.Row
	}
	return ""
}

func (x *UValues) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool  `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	Amount int32 `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internals_proto_update_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internals_proto_update_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_internals_proto_update_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *UpdateResponse) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_internals_proto_update_proto protoreflect.FileDescriptor

var file_internals_proto_update_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x70,
	0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x52, 0x08, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x73, 0x12, 0x20,
	0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x55, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x22, 0x51, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x52, 0x6f,
	0x77, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x31, 0x0a, 0x07, 0x55, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x52, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x52, 0x6f, 0x77,
	0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x40, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x39, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x12, 0x0d, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x1a, 0x0f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x79, 0x61, 0x64, 0x69, 0x69, 0x69, 0x67, 0x2e, 0x64,
	0x65, 0x76, 0x2f, 0x79, 0x64, 0x62, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internals_proto_update_proto_rawDescOnce sync.Once
	file_internals_proto_update_proto_rawDescData = file_internals_proto_update_proto_rawDesc
)

func file_internals_proto_update_proto_rawDescGZIP() []byte {
	file_internals_proto_update_proto_rawDescOnce.Do(func() {
		file_internals_proto_update_proto_rawDescData = protoimpl.X.CompressGZIP(file_internals_proto_update_proto_rawDescData)
	})
	return file_internals_proto_update_proto_rawDescData
}

var file_internals_proto_update_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internals_proto_update_proto_goTypes = []interface{}{
	(*UpdateValues)(nil),   // 0: UpdateValues
	(*MatchValues)(nil),    // 1: MatchValues
	(*UValues)(nil),        // 2: UValues
	(*UpdateResponse)(nil), // 3: UpdateResponse
}
var file_internals_proto_update_proto_depIdxs = []int32{
	1, // 0: UpdateValues.Matchers:type_name -> MatchValues
	2, // 1: UpdateValues.Values:type_name -> UValues
	0, // 2: Update.UpdateQuery:input_type -> UpdateValues
	3, // 3: Update.UpdateQuery:output_type -> UpdateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internals_proto_update_proto_init() }
func file_internals_proto_update_proto_init() {
	if File_internals_proto_update_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internals_proto_update_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internals_proto_update_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internals_proto_update_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internals_proto_update_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internals_proto_update_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internals_proto_update_proto_goTypes,
		DependencyIndexes: file_internals_proto_update_proto_depIdxs,
		MessageInfos:      file_internals_proto_update_proto_msgTypes,
	}.Build()
	File_internals_proto_update_proto = out.File
	file_internals_proto_update_proto_rawDesc = nil
	file_internals_proto_update_proto_goTypes = nil
	file_internals_proto_update_proto_depIdxs = nil
}
