// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.3
// source: internals/proto/insert.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsertValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table  string     `protobuf:"bytes,1,opt,name=Table,proto3" json:"Table,omitempty"`
	Values []*IValues `protobuf:"bytes,2,rep,name=Values,proto3" json:"Values,omitempty"`
}

func (x *InsertValues) Reset() {
	*x = InsertValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internals_proto_insert_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertValues) ProtoMessage() {}

func (x *InsertValues) ProtoReflect() protoreflect.Message {
	mi := &file_internals_proto_insert_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertValues.ProtoReflect.Descriptor instead.
func (*InsertValues) Descriptor() ([]byte, []int) {
	return file_internals_proto_insert_proto_rawDescGZIP(), []int{0}
}

func (x *InsertValues) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *InsertValues) GetValues() []*IValues {
	if x != nil {
		return x.Values
	}
	return nil
}

type InsertValuesMultiple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*InsertValues `protobuf:"bytes,1,rep,name=Values,proto3" json:"Values,omitempty"`
}

func (x *InsertValuesMultiple) Reset() {
	*x = InsertValuesMultiple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internals_proto_insert_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertValuesMultiple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertValuesMultiple) ProtoMessage() {}

func (x *InsertValuesMultiple) ProtoReflect() protoreflect.Message {
	mi := &file_internals_proto_insert_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertValuesMultiple.ProtoReflect.Descriptor instead.
func (*InsertValuesMultiple) Descriptor() ([]byte, []int) {
	return file_internals_proto_insert_proto_rawDescGZIP(), []int{1}
}

func (x *InsertValuesMultiple) GetValues() []*InsertValues {
	if x != nil {
		return x.Values
	}
	return nil
}

type IValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row   string `protobuf:"bytes,1,opt,name=Row,proto3" json:"Row,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *IValues) Reset() {
	*x = IValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internals_proto_insert_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IValues) ProtoMessage() {}

func (x *IValues) ProtoReflect() protoreflect.Message {
	mi := &file_internals_proto_insert_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IValues.ProtoReflect.Descriptor instead.
func (*IValues) Descriptor() ([]byte, []int) {
	return file_internals_proto_insert_proto_rawDescGZIP(), []int{2}
}

func (x *IValues) GetRow() string {
	if x != nil {
		return x.Row
	}
	return ""
}

func (x *IValues) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type InsertResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internals_proto_insert_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internals_proto_insert_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_internals_proto_insert_proto_rawDescGZIP(), []int{3}
}

func (x *InsertResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_internals_proto_insert_proto protoreflect.FileDescriptor

var file_internals_proto_insert_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46,
	0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x49, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x06,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x3d, 0x0a, 0x14, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x12, 0x25,
	0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x06, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x31, 0x0a, 0x07, 0x49, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x52,
	0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x28, 0x0a, 0x0e, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x32, 0x7a, 0x0a, 0x06, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x12, 0x2f, 0x0a, 0x0b,
	0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x0d, 0x2e, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x0f, 0x2e, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a,
	0x13, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x70, 0x6c, 0x65, 0x12, 0x15, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x1a, 0x0f, 0x2e, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x21,
	0x5a, 0x1f, 0x79, 0x61, 0x64, 0x69, 0x69, 0x69, 0x67, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x79, 0x64,
	0x62, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internals_proto_insert_proto_rawDescOnce sync.Once
	file_internals_proto_insert_proto_rawDescData = file_internals_proto_insert_proto_rawDesc
)

func file_internals_proto_insert_proto_rawDescGZIP() []byte {
	file_internals_proto_insert_proto_rawDescOnce.Do(func() {
		file_internals_proto_insert_proto_rawDescData = protoimpl.X.CompressGZIP(file_internals_proto_insert_proto_rawDescData)
	})
	return file_internals_proto_insert_proto_rawDescData
}

var file_internals_proto_insert_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internals_proto_insert_proto_goTypes = []interface{}{
	(*InsertValues)(nil),         // 0: InsertValues
	(*InsertValuesMultiple)(nil), // 1: InsertValuesMultiple
	(*IValues)(nil),              // 2: IValues
	(*InsertResponse)(nil),       // 3: InsertResponse
}
var file_internals_proto_insert_proto_depIdxs = []int32{
	2, // 0: InsertValues.Values:type_name -> IValues
	0, // 1: InsertValuesMultiple.Values:type_name -> InsertValues
	0, // 2: Insert.InsertQuery:input_type -> InsertValues
	1, // 3: Insert.InsertQueryMultiple:input_type -> InsertValuesMultiple
	3, // 4: Insert.InsertQuery:output_type -> InsertResponse
	3, // 5: Insert.InsertQueryMultiple:output_type -> InsertResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internals_proto_insert_proto_init() }
func file_internals_proto_insert_proto_init() {
	if File_internals_proto_insert_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internals_proto_insert_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internals_proto_insert_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertValuesMultiple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internals_proto_insert_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internals_proto_insert_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internals_proto_insert_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internals_proto_insert_proto_goTypes,
		DependencyIndexes: file_internals_proto_insert_proto_depIdxs,
		MessageInfos:      file_internals_proto_insert_proto_msgTypes,
	}.Build()
	File_internals_proto_insert_proto = out.File
	file_internals_proto_insert_proto_rawDesc = nil
	file_internals_proto_insert_proto_goTypes = nil
	file_internals_proto_insert_proto_depIdxs = nil
}
